# -*- coding: utf-8 -*-
"""PY2022CD-Tugas01-Muhammad Iqbal Widiansyah-2117051011.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/140DCyZ8T4Ij4WZOlR5q73XWxDR600CgC
"""

number1, number2, number3 = eval(input("Masukkan Angka: ")) 
sum = (number1 * number1 + number2 * number2 + number3 * number3) 
print("Penjumlahan Dari", number1, "^2,", number2, "^2,", number3, "^2 Adalah", sum)